id: I6FD6E796
legacy_id: P001790
ocr_import_info:
  bdrc_scan_id: W1KG24057
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:45:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:35:07.902444+00:00'
last_modified: 2022-08-27 15:35:21.106874
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG24057
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG24057
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་གུང་ཐང་པའི་ལུགས་ཟུང་བསླབ་བྱ་ལེ་ཚན་སུམ་ཅུ་ལྷག་དང་། དཔལ་སྤྲུལ་རིན་པོ་ཆེའི་གསུང་ལུགས་གཉིས་སྙིང་བཅུད་བཅས།
  author: གུང་ཐང་བསྟན་པའི་སྒྲོན་མེ།
statistics:
  ocr_word_mean_confidence_index: 0.960779475926727
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG24209:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24209
      total_pages: 112
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24209.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.960779475926727
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
