id: P001790
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24057
  title: རྗེ་གུང་ཐང་པའི་ལུགས་ཟུང་བསླབ་བྱ་ལེ་ཚན་སུམ་ཅུ་ལྷག་དང་། དཔལ་སྤྲུལ་རིན་པོ་ཆེའི་གསུང་ལུགས་གཉིས་སྙིང་བཅུད་བཅས།
  author: ''
  volumes: {}
