id: P001790
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:21:47.619770
source_metadata:
  id: bdr:W1KG24057
  title: རྗེ་གུང་ཐང་པའི་ལུགས་ཟུང་བསླབ་བྱ་ལེ་ཚན་སུམ་ཅུ་ལྷག་དང་། དཔལ་སྤྲུལ་རིན་པོ་ཆེའི་གསུང་ལུགས་གཉིས་སྙིང་བཅུད་བཅས།
  author: ''
  volumes:
    a12deafdaaee4233a3e5aacb1a796b16:
      image_group_id: I1KG24209
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
